name: Packer CI

on: [pull_request]

jobs:
  packer-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
        unzip packer_1.7.2_linux_amd64.zip
        chmod +x packer
        mv packer /usr/local/bin
      shell: bash

    - name: Run packer init
      run: packer init aws.debian.pkr.hcl

    - name: Format Packer Template
      run: packer fmt -check=true aws.debian.pkr.hcl

    - name: Validate Packer Template
      run: packer validate aws.debian.pkr.hcl
